### ISSUE TITLE
Custom tag queries

### ISSUE THREAD

**Issue by PDPENG** [tandpfun/tandpfun#1]
Hello, may I ask how to generate such a label

![image](https://user-images.githubusercontent.com/86602255/170174419-3cf99360-59a7-442d-acf4-4287de6ff4ab.png)

After I created an account at [discord](https://discord.com), I added the user ID and displayed the user-defined label as shown in the figure below

![image](https://user-images.githubusercontent.com/86602255/170174586-1096c5f6-9949-41a2-8299-c727d19b37b1.png)

Is it my fault? I am looking forward to your reply

**Comment by tandpfun** [comment]
It's not my project, but I think you might be able to get it working by joining the https://discord.gg/WeCer3J server.

**Comment by tandpfun** [comment]
I can't really help you with it tho (and I don't think that server can) since that website isn't out yet.

**Comment by PDPENG** [comment]
Thank you for your answer
